import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
public class personaldetails extends javax.swing.JFrame {

       private final String loggedInUsername;

    /**
     * Creates new form personaldetails
     */
    public personaldetails(String username) {
        this.loggedInUsername = username;
        initComponents();
        displayUserData();
    }

    personaldetails() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
     private void displayUserData() {
try {
        // Establish database connection
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/esheba", "root", "@2003Moon2003");

        // Create prepared statement
        String query = "SELECT * FROM esheba WHERE username = ?";
        try (PreparedStatement preparedStatement = conn.prepareStatement(query)) {
            preparedStatement.setString(1, loggedInUsername);

            // Execute the query
            ResultSet rs = preparedStatement.executeQuery();

            // Get the table model
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            // Clear the table
            model.setRowCount(0);

            // Iterate through the result set and add rows to the table
            while (rs.next()) {
                Object[] row = {
                    rs.getString("Name"),
                    rs.getString("FathersName"),
                    rs.getString("MothersName"),
                    rs.getString("BirthRegNo"),
                    rs.getString("NidNo"),
                    rs.getString("PhoneNo"),
                    rs.getString("Email"),
                    rs.getString("PresentAddress"),
                    rs.getString("PermanentAddress"),
                    rs.getString("BloodGroup"),
                    rs.getString("Religion"),
                    rs.getString("BirthDate")
                };
                model.addRow(row);
            }

            // Close the result set and connection
            rs.close();
            conn.close();
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "FathersName", "MothersName", "BirthRegNo", "NidNo", "PhoneNo", "Email", "present Address", "Parmanent Address", "Blood Group", "Religion", "BirthDate"
            }
        ));
        jTable1.setAlignmentX(1.0F);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 211, 1170, 90));

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 343, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 570));

        jMenu1.setText("Logout");

        jMenuItem1.setText("Logout");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String username = JOptionPane.showInputDialog(this, "Enter your username:");

        if (username != null && !username.isEmpty()) {
            displayUserData(username);
        } else {
            JOptionPane.showMessageDialog(this, "Please enter a valid username.");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
loginpage back = new loginpage ();
back.setVisible(true);
setVisible(false);
this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
firstpage logout = new firstpage ();
logout.setVisible(true);
setVisible(false);
this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed
private void displayUserData(String username) {
        try {
            // Establish database connection
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/esheba", "root", "@2003Moon2003");

            // Create prepared statement
            String query = "SELECT * FROM esheba WHERE username = ?";
            try (PreparedStatement preparedStatement = conn.prepareStatement(query)) {
                preparedStatement.setString(1, username);

                // Execute the query
                ResultSet rs = preparedStatement.executeQuery();

                // Get the table model
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

                // Clear the table
                model.setRowCount(0);

                // Check if the username exists in the database
                if (rs.next()) {
                    // Add the user's details to the table
                    Object[] row = {
                        rs.getString("Name"),
                        rs.getString("FathersName"),
                        rs.getString("MothersName"),
                        rs.getString("BirthRegNo"),
                        rs.getString("NidNo"),
                        rs.getString("PhoneNo"),
                        rs.getString("Email"),
                        rs.getString("PresentAddress"),
                        rs.getString("PermanentAddress"),
                        rs.getString("BloodGroup"),
                        rs.getString("Religion"),
                        rs.getString("BirthDate")
                    };
                    model.addRow(row);
                } else {
                    JOptionPane.showMessageDialog(this, "User with username '" + username + "' not found.");
                }

                // Close the result set and connection
                rs.close();
                conn.close();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }                                        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(personaldetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(personaldetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(personaldetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(personaldetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Provide a valid username here
                String username = "your_username";
                new personaldetails(username).setVisible(true);
            }


        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
